matrix:
  include:
    # works on Precise and Trusty
    - language: python
      python: 
        - 3.6
        - 3.7
      before_install:
        - eval "${MATRIX_EVAL}"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - pip install -r requirements.txt && alias g++="g++-7 -std=c++11" && alias gcc="gcc-7 -std=c11" && cd rakan/ && touch rakan.pyx && touch rakan.pxd && python setup.py build_ext --inplace && cd .. 
      script:
        - py.test --ignore=xayah --doctest-cython