site_name: UW WXML
theme:
  name: 'material'
  logo: 'ghost.png'
  palette:
    primary: deep purple
    accent: deep purple
nav:
  - The Gerrymandering Project: index.md
  - Understanding the Project:
    - Definitions: understand/index.md
    - Examples: understand/examples.md
  - Building a Solution:
    - Our Solution: solution/index.md
    - Previous Research: solution/previous.md
    - Autumn 2018: solution/F18.md
  - About Us: about.md
markdown_extensions:
  - pymdownx.arithmatex
  - footnotes
  - codehilite
  - admonition
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
